#!/usr/bin/env python3
"""Prepare the supplied Goalunit CSV files for the TypeScript frontend."""

import argparse
import csv
from pathlib import Path


CLUB_FIELDS = (
    "competitionName",
    "seasonName",
    "clubId",
    "clubName",
    "transferkpi",
    "totalAssets",
    "totalRevenues",
)
PLAYER_FIELDS = (
    "playerId",
    "playerName",
    "seasonName",
    "contractExpiration",
    "fairPrice",
)


def clean(value: str | None) -> str | None:
    value = (value or "").strip()
    return value or None


def number(value: str | None, integer: bool = False) -> int | float | None:
    value = clean(value)
    if value is None:
        return None
    parsed = float(value)
    return int(parsed) if integer else parsed


def read_csv(path: Path, fields: tuple[str, ...]) -> list[dict[str, str | None]]:
    with path.open(newline="", encoding="utf-8-sig") as source:
        return [
            {field: clean(row.get(field)) for field in fields}
            for row in csv.DictReader(source)
        ]


def prepare_clubs(path: Path) -> list[dict[str, object]]:
    records = []
    seen: set[tuple[str | None, str | None, str | None]] = set()
    for row in read_csv(path, CLUB_FIELDS):
        key = (row["seasonName"], row["clubId"], row["clubName"])
        if key in seen:
            continue
        seen.add(key)
        records.append(
            {
                "competitionName": row["competitionName"],
                "seasonName": row["seasonName"],
                "clubId": number(row["clubId"], integer=True),
                "clubName": row["clubName"],
                "transferKpi": number(row["transferkpi"]),
                "totalAssets": number(row["totalAssets"], integer=True),
                "totalRevenues": number(row["totalRevenues"], integer=True),
            }
        )
    return records


def prepare_players(path: Path) -> list[dict[str, object]]:
    records: dict[tuple[int | None, str | None], dict[str, object]] = {}
    for row in read_csv(path, PLAYER_FIELDS):
        player_id = number(row["playerId"], integer=True)
        key = (player_id, row["seasonName"])
        record = {
            "playerId": player_id,
            "playerName": row["playerName"],
            "seasonName": row["seasonName"],
            "contractExpiration": row["contractExpiration"],
            "fairPrice": number(row["fairPrice"]),
            "clubId": None,
        }
        current = records.get(key)
        if current is None or (record["fairPrice"] or 0) > (current["fairPrice"] or 0):
            records[key] = record
    return sorted(
        records.values(),
        key=lambda player: (-(player["fairPrice"] or 0), player["playerName"] or ""),
    )


def ts(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return str(value)


def write_typescript(
    output: Path, clubs: list[dict[str, object]], players: list[dict[str, object]]
) -> None:
    lines = [
        "// Generated by scripts/prepare_data.py. Do not edit manually.",
        "",
        "export type PreparedClub = {",
        "  competitionName: string | null",
        "  seasonName: string | null",
        "  clubId: number | null",
        "  clubName: string | null",
        "  transferKpi: number | null",
        "  totalAssets: number | null",
        "  totalRevenues: number | null",
        "}",
        "",
        "export type PreparedPlayer = {",
        "  playerId: number | null",
        "  playerName: string | null",
        "  seasonName: string | null",
        "  contractExpiration: string | null",
        "  fairPrice: number | null",
        "  clubId: number | null",
        "}",
        "",
        "export const clubs: PreparedClub[] = ",
    ]
    lines.append(json_like(clubs) + ";")
    lines.extend(["", "export const players: PreparedPlayer[] = "])
    lines.append(json_like(players) + ";")
    lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def json_like(records: list[dict[str, object]]) -> str:
    rows = []
    for record in records:
        fields = ", ".join(f"{key}: {ts(value)}" for key, value in record.items())
        rows.append("  { " + fields + " }")
    return "[\n" + ",\n".join(rows) + "\n]"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clubs", type=Path, required=True, help="Path to clubs.csv")
    parser.add_argument(
        "--players", type=Path, required=True, help="Path to players.csv"
    )
    parser.add_argument(
        "--output", type=Path, default=Path("src/data/goalunitData.generated.ts")
    )
    args = parser.parse_args()
    clubs = prepare_clubs(args.clubs)
    players = prepare_players(args.players)
    write_typescript(args.output, clubs, players)
    print(
        f"Prepared {len(clubs)} club records and {len(players)} player records -> {args.output}"
    )
    print(
        "Note: players.csv has no clubId column; generated player clubId values are null."
    )


if __name__ == "__main__":
    main()
