// Generated by scripts/prepare_events.py. Do not edit manually.

export type ClubPlayingStyleSummary = {
  clubId: number
  clubName: string
  seasonId: number
  seasonName: string
  matches: number
  passes: number
  passCompletionPct: number
  shots: number
  expectedGoals: number
  possessionValue: number
  duelsWon: number
  ballRecoveries: number
}

export type PlayerClubAssignment = {
  playerId: number
  seasonId: number
  clubId: number
}

export const eventRowCount = 2249813
export const eventsDataAsOf = "2025-05-25"

export const clubPlayingStyleSummaries: ClubPlayingStyleSummary[] = [
  {
    "clubId": 1255,
    "clubName": "Arsenal",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 23468,
    "passCompletionPct": 85.5,
    "shots": 663,
    "expectedGoals": 75.85,
    "possessionValue": 3762.9,
    "duelsWon": 1605,
    "ballRecoveries": 4814
  },
  {
    "clubId": 1281,
    "clubName": "Aston Villa",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 19915,
    "passCompletionPct": 83.7,
    "shots": 522,
    "expectedGoals": 67.96,
    "possessionValue": 3467.3,
    "duelsWon": 1282,
    "ballRecoveries": 4231
  },
  {
    "clubId": 1423,
    "clubName": "Bournemouth",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 16929,
    "passCompletionPct": 76.3,
    "shots": 547,
    "expectedGoals": 61.91,
    "possessionValue": 3006.1,
    "duelsWon": 1724,
    "ballRecoveries": 5413
  },
  {
    "clubId": 1444,
    "clubName": "Brentford",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 17891,
    "passCompletionPct": 76.0,
    "shots": 474,
    "expectedGoals": 61.61,
    "possessionValue": 2908.5,
    "duelsWon": 1725,
    "ballRecoveries": 5487
  },
  {
    "clubId": 1461,
    "clubName": "Brighton",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 25321,
    "passCompletionPct": 86.9,
    "shots": 558,
    "expectedGoals": 60.06,
    "possessionValue": 4102.8,
    "duelsWon": 1453,
    "ballRecoveries": 4664
  },
  {
    "clubId": 1503,
    "clubName": "Burnley",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 18953,
    "passCompletionPct": 78.1,
    "shots": 441,
    "expectedGoals": 43.81,
    "possessionValue": 3063.2,
    "duelsWon": 1507,
    "ballRecoveries": 5296
  },
  {
    "clubId": 1570,
    "clubName": "Chelsea",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 23940,
    "passCompletionPct": 85.5,
    "shots": 559,
    "expectedGoals": 78.64,
    "possessionValue": 3873.9,
    "duelsWon": 1563,
    "ballRecoveries": 4795
  },
  {
    "clubId": 1680,
    "clubName": "Crystal Palace",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 17857,
    "passCompletionPct": 77.5,
    "shots": 453,
    "expectedGoals": 50.74,
    "possessionValue": 2739.3,
    "duelsWon": 1733,
    "ballRecoveries": 5336
  },
  {
    "clubId": 1803,
    "clubName": "Everton",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 16800,
    "passCompletionPct": 74.0,
    "shots": 501,
    "expectedGoals": 56.99,
    "possessionValue": 2794.1,
    "duelsWon": 1748,
    "ballRecoveries": 5609
  },
  {
    "clubId": 1861,
    "clubName": "Fulham",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 20801,
    "passCompletionPct": 81.5,
    "shots": 502,
    "expectedGoals": 56.29,
    "possessionValue": 3520.5,
    "duelsWon": 1558,
    "ballRecoveries": 4992
  },
  {
    "clubId": 2121,
    "clubName": "Liverpool",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 25053,
    "passCompletionPct": 84.2,
    "shots": 796,
    "expectedGoals": 96.88,
    "possessionValue": 4346.9,
    "duelsWon": 1629,
    "ballRecoveries": 5380
  },
  {
    "clubId": 2157,
    "clubName": "Luton Town",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 16359,
    "passCompletionPct": 74.2,
    "shots": 438,
    "expectedGoals": 45.94,
    "possessionValue": 2776.0,
    "duelsWon": 1657,
    "ballRecoveries": 5451
  },
  {
    "clubId": 2175,
    "clubName": "Manchester City",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 28037,
    "passCompletionPct": 88.9,
    "shots": 703,
    "expectedGoals": 84.69,
    "possessionValue": 4464.3,
    "duelsWon": 1255,
    "ballRecoveries": 4273
  },
  {
    "clubId": 2188,
    "clubName": "Manchester United",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 20418,
    "passCompletionPct": 80.4,
    "shots": 552,
    "expectedGoals": 60.96,
    "possessionValue": 3392.8,
    "duelsWon": 1665,
    "ballRecoveries": 5249
  },
  {
    "clubId": 2263,
    "clubName": "Newcastle United",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 20518,
    "passCompletionPct": 81.5,
    "shots": 555,
    "expectedGoals": 75.27,
    "possessionValue": 3362.3,
    "duelsWon": 1647,
    "ballRecoveries": 5036
  },
  {
    "clubId": 2304,
    "clubName": "Nottingham Forest",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 16951,
    "passCompletionPct": 75.9,
    "shots": 444,
    "expectedGoals": 46.57,
    "possessionValue": 2739.2,
    "duelsWon": 1603,
    "ballRecoveries": 5221
  },
  {
    "clubId": 2501,
    "clubName": "Sheffield United",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 14713,
    "passCompletionPct": 72.0,
    "shots": 368,
    "expectedGoals": 41.12,
    "possessionValue": 2168.1,
    "duelsWon": 1651,
    "ballRecoveries": 5348
  },
  {
    "clubId": 2689,
    "clubName": "Tottenham Hotspur",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 24578,
    "passCompletionPct": 85.5,
    "shots": 592,
    "expectedGoals": 70.34,
    "possessionValue": 4013.6,
    "duelsWon": 1650,
    "ballRecoveries": 4884
  },
  {
    "clubId": 2771,
    "clubName": "West Ham United",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 17241,
    "passCompletionPct": 77.7,
    "shots": 453,
    "expectedGoals": 54.26,
    "possessionValue": 2740.7,
    "duelsWon": 1695,
    "ballRecoveries": 5233
  },
  {
    "clubId": 2833,
    "clubName": "Wolverhampton Wanderers",
    "seasonId": 1773,
    "seasonName": "2023/2024",
    "matches": 38,
    "passes": 20196,
    "passCompletionPct": 80.7,
    "shots": 433,
    "expectedGoals": 49.56,
    "possessionValue": 3198.3,
    "duelsWon": 1615,
    "ballRecoveries": 5139
  },
  {
    "clubId": 1255,
    "clubName": "Arsenal",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 21477,
    "passCompletionPct": 84.8,
    "shots": 544,
    "expectedGoals": 64.23,
    "possessionValue": 3395.1,
    "duelsWon": 1416,
    "ballRecoveries": 4498
  },
  {
    "clubId": 1281,
    "clubName": "Aston Villa",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 18932,
    "passCompletionPct": 82.9,
    "shots": 486,
    "expectedGoals": 62.32,
    "possessionValue": 3144.1,
    "duelsWon": 1333,
    "ballRecoveries": 4390
  },
  {
    "clubId": 1423,
    "clubName": "Bournemouth",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 18455,
    "passCompletionPct": 76.7,
    "shots": 579,
    "expectedGoals": 68.96,
    "possessionValue": 3147.8,
    "duelsWon": 1620,
    "ballRecoveries": 5611
  },
  {
    "clubId": 1444,
    "clubName": "Brentford",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 18537,
    "passCompletionPct": 78.0,
    "shots": 443,
    "expectedGoals": 64.56,
    "possessionValue": 3087.9,
    "duelsWon": 1514,
    "ballRecoveries": 5229
  },
  {
    "clubId": 1461,
    "clubName": "Brighton",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 20491,
    "passCompletionPct": 81.9,
    "shots": 530,
    "expectedGoals": 65.43,
    "possessionValue": 3427.2,
    "duelsWon": 1564,
    "ballRecoveries": 4974
  },
  {
    "clubId": 1570,
    "clubName": "Chelsea",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 22218,
    "passCompletionPct": 84.6,
    "shots": 596,
    "expectedGoals": 71.14,
    "possessionValue": 3642.1,
    "duelsWon": 1341,
    "ballRecoveries": 4542
  },
  {
    "clubId": 1680,
    "clubName": "Crystal Palace",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 17383,
    "passCompletionPct": 75.9,
    "shots": 515,
    "expectedGoals": 68.96,
    "possessionValue": 2672.2,
    "duelsWon": 1587,
    "ballRecoveries": 5520
  },
  {
    "clubId": 1803,
    "clubName": "Everton",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 16680,
    "passCompletionPct": 76.5,
    "shots": 408,
    "expectedGoals": 47.59,
    "possessionValue": 2816.9,
    "duelsWon": 1611,
    "ballRecoveries": 5128
  },
  {
    "clubId": 1861,
    "clubName": "Fulham",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 21078,
    "passCompletionPct": 82.2,
    "shots": 519,
    "expectedGoals": 56.16,
    "possessionValue": 3561.7,
    "duelsWon": 1517,
    "ballRecoveries": 4907
  },
  {
    "clubId": 2034,
    "clubName": "Ipswich Town",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 16183,
    "passCompletionPct": 77.5,
    "shots": 380,
    "expectedGoals": 40.63,
    "possessionValue": 2513.6,
    "duelsWon": 1545,
    "ballRecoveries": 4909
  },
  {
    "clubId": 2083,
    "clubName": "Leicester City",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 18611,
    "passCompletionPct": 79.8,
    "shots": 338,
    "expectedGoals": 38.06,
    "possessionValue": 2870.7,
    "duelsWon": 1513,
    "ballRecoveries": 4977
  },
  {
    "clubId": 2121,
    "clubName": "Liverpool",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 22810,
    "passCompletionPct": 84.4,
    "shots": 649,
    "expectedGoals": 84.67,
    "possessionValue": 3841.9,
    "duelsWon": 1360,
    "ballRecoveries": 4833
  },
  {
    "clubId": 2175,
    "clubName": "Manchester City",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 25163,
    "passCompletionPct": 88.2,
    "shots": 606,
    "expectedGoals": 70.91,
    "possessionValue": 4098.6,
    "duelsWon": 1182,
    "ballRecoveries": 4117
  },
  {
    "clubId": 2188,
    "clubName": "Manchester United",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 21679,
    "passCompletionPct": 83.1,
    "shots": 531,
    "expectedGoals": 57.07,
    "possessionValue": 3353.4,
    "duelsWon": 1645,
    "ballRecoveries": 5029
  },
  {
    "clubId": 2263,
    "clubName": "Newcastle United",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 19795,
    "passCompletionPct": 81.9,
    "shots": 522,
    "expectedGoals": 66.71,
    "possessionValue": 3201.2,
    "duelsWon": 1561,
    "ballRecoveries": 4950
  },
  {
    "clubId": 2304,
    "clubName": "Nottingham Forest",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 16217,
    "passCompletionPct": 75.1,
    "shots": 463,
    "expectedGoals": 50.54,
    "possessionValue": 2575.4,
    "duelsWon": 1467,
    "ballRecoveries": 5259
  },
  {
    "clubId": 2550,
    "clubName": "Southampton",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 19736,
    "passCompletionPct": 82.6,
    "shots": 348,
    "expectedGoals": 38.5,
    "possessionValue": 2990.1,
    "duelsWon": 1532,
    "ballRecoveries": 4584
  },
  {
    "clubId": 2689,
    "clubName": "Tottenham Hotspur",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 20912,
    "passCompletionPct": 82.3,
    "shots": 494,
    "expectedGoals": 62.85,
    "possessionValue": 3445.4,
    "duelsWon": 1432,
    "ballRecoveries": 4868
  },
  {
    "clubId": 2771,
    "clubName": "West Ham United",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 19844,
    "passCompletionPct": 80.4,
    "shots": 478,
    "expectedGoals": 53.28,
    "possessionValue": 3034.8,
    "duelsWon": 1712,
    "ballRecoveries": 5206
  },
  {
    "clubId": 2833,
    "clubName": "Wolverhampton Wanderers",
    "seasonId": 862,
    "seasonName": "2024/2025",
    "matches": 38,
    "passes": 19162,
    "passCompletionPct": 80.2,
    "shots": 433,
    "expectedGoals": 48.71,
    "possessionValue": 3021.5,
    "duelsWon": 1514,
    "ballRecoveries": 4923
  }
]

export const playerClubAssignments: PlayerClubAssignment[] = [
  {
    "playerId": 30428,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 30435,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 30739,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 32034,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 33606,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 34197,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 35946,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 37694,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 37695,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 37760,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 37765,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 37785,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 37791,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 37798,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 37975,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 37976,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 37980,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 37984,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 37995,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 38057,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 38075,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 38081,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 38111,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 38120,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 38152,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 38191,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 38222,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 38288,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 38327,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 38403,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 38405,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 38473,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 38753,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 38754,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 38764,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 38789,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 38828,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 38901,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 38965,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 39006,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 39174,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 39224,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 39407,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 39464,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 39724,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 39893,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 39914,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 40790,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 40805,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 41004,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 41394,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 41961,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 42097,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 42516,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 44355,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 44415,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 44454,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 44554,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 44780,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 45414,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 50266,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 50645,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 54455,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 54520,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 54603,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 54723,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 54728,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 57182,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 58440,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 65958,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 66078,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 68705,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 68735,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 77763,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 78430,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 78683,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 83445,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 88511,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 88690,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 88784,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 95525,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 96458,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 97683,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 97731,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 108645,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 120167,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 129239,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 129703,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 136380,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 143867,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 156981,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 157546,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 159131,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 159198,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 167698,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 171936,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 174720,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 174751,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 186424,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 186932,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 189089,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 191291,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 193655,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 194139,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 195007,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 196943,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 197708,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 199150,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 200064,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 203771,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 205833,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 206041,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 207905,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 208466,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 208490,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 208714,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 208774,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 209687,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 211009,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 212889,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 213830,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 214689,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 215363,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 220428,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 222217,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 222445,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 222608,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 227010,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 227011,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 227402,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 228276,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 228560,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 232643,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 235705,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 236788,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 236793,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 241287,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 242283,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 242811,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 243026,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 243028,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 243983,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 244587,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 244891,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 244910,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 245008,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 245735,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 245747,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 246100,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 246102,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 247174,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 247183,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 249485,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 251381,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 251382,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 254219,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 254480,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 255337,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 255993,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 256309,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 257123,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 258117,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 258327,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 259022,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 260752,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 261069,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 261407,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 266530,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 268462,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 269158,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 271397,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 271857,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 272082,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 274012,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 274764,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 274841,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 274843,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 274896,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 274973,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 276065,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 276250,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 276482,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 276506,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 276512,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 276520,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 276538,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 276539,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 277384,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 277386,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 278689,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 278728,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 279211,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 280231,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 280655,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 283478,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 283539,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 285365,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 286146,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 287080,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 287624,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 288677,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 289354,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 289801,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 289804,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 290179,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 290470,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 290899,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 291630,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 291865,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 292128,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 292997,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 293232,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 294347,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 295463,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 297480,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 298501,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 299094,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 299748,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 300459,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 301581,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 302484,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 302642,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 302653,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 303876,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 305207,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 307036,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 308340,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 308388,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 308427,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 308450,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 308514,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 308525,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 308529,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 309501,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 309523,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 309526,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 309541,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 310262,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 310287,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 311850,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 312609,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 312790,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 313189,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 313196,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 313197,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 314385,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 314406,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 317651,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 317658,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 318247,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 318268,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 318733,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 320355,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 320421,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 320457,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 322623,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 322629,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 322953,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 323142,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 323975,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 324212,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 324999,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 325762,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 326151,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 326285,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 327189,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 328209,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 332307,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 333448,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 333988,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 339315,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 339384,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 340571,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 341716,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 341934,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 342306,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 342401,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 342411,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 342419,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 342429,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 342434,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 342559,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 342609,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 342625,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 342736,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 342960,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 342989,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 343129,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 343136,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 343239,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 343358,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 343728,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 343735,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 343774,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 343794,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 344143,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 344324,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 345431,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 345861,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 346541,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 347341,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 347473,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 349580,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 350596,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 350714,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 350729,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 350829,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 350900,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 351331,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 351767,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 353045,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 354176,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 354801,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 354836,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 356536,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 356954,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 357423,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 357989,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 358115,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 358977,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 359113,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 361802,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 362296,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 362318,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 363248,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 363343,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 363542,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 363544,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 365262,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 365306,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 365347,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 368720,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 368875,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 369370,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 371213,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 371832,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 372369,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 373784,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 374342,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 374418,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 374562,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 374576,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 377030,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 377574,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 380399,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 381432,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 384037,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 384437,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 385436,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 385494,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 385503,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 386352,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 386977,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 388336,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 388353,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 389423,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 389428,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 390586,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 391178,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 391983,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 394213,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 394306,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 394409,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 394457,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 395238,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 395369,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 396361,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 396376,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 396391,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 396576,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 396826,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 397364,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 399923,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 399946,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 400512,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 400932,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 401856,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 401925,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 402020,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 402740,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 402963,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 403768,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 405619,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 405856,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 406778,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 406808,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 406868,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 407850,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 409931,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 411080,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 411361,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 411678,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 415564,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 416412,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 417444,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 417629,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 418932,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 424985,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 426448,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 426867,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 426993,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 427007,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 427287,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 427440,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 428248,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 428405,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 429209,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 430418,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 430419,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 431102,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 432671,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 432922,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 434416,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 434427,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 435523,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 435583,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 435650,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 437015,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 437929,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 438555,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 438680,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 438767,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 440073,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 441115,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 442408,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 442691,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 442696,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 442878,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 444014,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 445648,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 445958,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 447310,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 447965,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 448190,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 448954,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 452877,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 452959,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 454606,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 456874,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 456875,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 456892,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 457059,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 457457,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 457963,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 458096,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 458703,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 458759,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 458783,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 458785,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 458944,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 459611,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 459761,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 461401,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 462206,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 462322,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 464836,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 465578,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 466868,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 468210,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 471367,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 475416,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 475577,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 476168,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 476440,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 478352,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 481568,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 481757,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 481983,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 482808,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 484062,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 484117,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 484172,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 484439,
    "seasonId": 862,
    "clubId": 2034
  },
  {
    "playerId": 485102,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 485487,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 485874,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 486076,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 487918,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 492205,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 497655,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 500019,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 505485,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 505978,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 508497,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 508498,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 508912,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 513086,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 513136,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 513845,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 519236,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 527168,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 530622,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 533917,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 534434,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 534981,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 535689,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 536171,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 537983,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 540241,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 542981,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 544580,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 544583,
    "seasonId": 862,
    "clubId": 1255
  },
  {
    "playerId": 545987,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 556961,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 557762,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 560081,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 560124,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 560313,
    "seasonId": 862,
    "clubId": 2263
  },
  {
    "playerId": 561752,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 562151,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 566766,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 566770,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 567586,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 568743,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 570398,
    "seasonId": 862,
    "clubId": 1281
  },
  {
    "playerId": 571655,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 585320,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 588262,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 589177,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 589537,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 590179,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 594159,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 594344,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 595568,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 599876,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 600290,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 600705,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 607788,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 616175,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 618561,
    "seasonId": 862,
    "clubId": 2550
  },
  {
    "playerId": 620830,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 621962,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 628687,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 657051,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 669566,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 730490,
    "seasonId": 862,
    "clubId": 2833
  },
  {
    "playerId": 733362,
    "seasonId": 862,
    "clubId": 2083
  },
  {
    "playerId": 7086990,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 7088834,
    "seasonId": 862,
    "clubId": 2304
  },
  {
    "playerId": 7091820,
    "seasonId": 862,
    "clubId": 2121
  },
  {
    "playerId": 7092009,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 7092107,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 7092345,
    "seasonId": 862,
    "clubId": 1461
  },
  {
    "playerId": 7092623,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 7092690,
    "seasonId": 862,
    "clubId": 1861
  },
  {
    "playerId": 7092691,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 7092756,
    "seasonId": 862,
    "clubId": 2689
  },
  {
    "playerId": 7093961,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 7094225,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 7100538,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 7100680,
    "seasonId": 862,
    "clubId": 1680
  },
  {
    "playerId": 7101007,
    "seasonId": 862,
    "clubId": 2175
  },
  {
    "playerId": 7102474,
    "seasonId": 862,
    "clubId": 1444
  },
  {
    "playerId": 7102500,
    "seasonId": 862,
    "clubId": 2188
  },
  {
    "playerId": 7102955,
    "seasonId": 862,
    "clubId": 1803
  },
  {
    "playerId": 7103399,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 11792568,
    "seasonId": 862,
    "clubId": 1423
  },
  {
    "playerId": 44618715,
    "seasonId": 862,
    "clubId": 1570
  },
  {
    "playerId": 71458650,
    "seasonId": 862,
    "clubId": 2771
  },
  {
    "playerId": 30428,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 30435,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 30473,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 30739,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 32034,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 33524,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 33559,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 33993,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 34197,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 34587,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 35946,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 37694,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 37695,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 37760,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 37765,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 37785,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 37791,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 37804,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 37822,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 37881,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 37957,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 37965,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 37975,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 37980,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 37984,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 37995,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 38057,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 38075,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 38081,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 38111,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 38152,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 38191,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 38222,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 38224,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 38288,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 38299,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 38327,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 38378,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 38388,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 38405,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 38473,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 38588,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 38646,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 38753,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 38754,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 38764,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 38767,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 38789,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 38901,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 38965,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 39006,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 39009,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 39026,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 39174,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 39184,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 39195,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 39204,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 39224,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 39407,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 39724,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 39893,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 39914,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 40161,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 40790,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 40805,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 41277,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 41394,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 41888,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 41961,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 42097,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 43155,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 44415,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 44458,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 44514,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 44554,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 44780,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 44808,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 45144,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 46385,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 49756,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 50266,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 50438,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 50645,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 54455,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 54520,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 54603,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 54723,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 54728,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 54803,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 54868,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 57182,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 58440,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 65791,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 65958,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 66078,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 66694,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 68497,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 68705,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 68735,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 77763,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 78430,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 78683,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 80988,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 83177,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 83445,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 88690,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 95525,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 96466,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 97683,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 97731,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 108645,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 120167,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 129239,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 129703,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 136380,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 143853,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 143867,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 151337,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 156981,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 157168,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 157346,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 157347,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 157356,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 157531,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 157537,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 157546,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 157909,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 159131,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 164969,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 167698,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 169594,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 171351,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 171936,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 174720,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 174736,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 174751,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 185350,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 185421,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 186424,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 186932,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 189089,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 191291,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 193655,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 194139,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 195007,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 196943,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 197708,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 198382,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 199150,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 199255,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 200064,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 203771,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 203800,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 204732,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 206041,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 207224,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 207905,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 208714,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 208774,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 208843,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 209687,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 211009,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 211187,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 213830,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 215844,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 220174,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 220428,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 222100,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 222217,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 222445,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 227010,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 227011,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 227402,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 228560,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 230304,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 232643,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 233859,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 235705,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 236788,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 241287,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 242283,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 242782,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 243025,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 243026,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 243028,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 243983,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 244100,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 244586,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 244587,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 244910,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 245008,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 245089,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 245218,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 245735,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 245747,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 246102,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 246185,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 247175,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 247756,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 248759,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 250888,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 251381,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 251382,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 251483,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 254219,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 254480,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 255337,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 255993,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 257123,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 258117,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 258327,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 259022,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 260565,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 261069,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 266377,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 266530,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 268462,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 268925,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 271857,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 274841,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 274843,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 274896,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 274973,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 276065,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 276250,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 276482,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 276506,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 276512,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 276520,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 276530,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 276538,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 276539,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 277384,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 277386,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 277523,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 277654,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 278689,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 279211,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 280231,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 281898,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 283478,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 283630,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 285365,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 286146,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 287080,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 287624,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 288677,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 289354,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 290021,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 290899,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 291630,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 291865,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 292128,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 293232,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 294347,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 297480,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 297487,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 298355,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 299094,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 299748,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 300153,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 300427,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 301581,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 302581,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 302642,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 302653,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 303876,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 305207,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 307036,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 308340,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 308413,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 308427,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 308450,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 308525,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 308529,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 309432,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 309445,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 309501,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 309523,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 309526,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 309541,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 309614,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 310262,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 310287,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 311826,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 312019,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 312790,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 313104,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 313194,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 313197,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 314385,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 314406,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 317651,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 318247,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 318268,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 318733,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 319152,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 320355,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 320421,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 320457,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 322614,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 322623,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 322629,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 323142,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 323975,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 324212,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 324999,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 326151,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 327189,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 328209,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 332307,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 333448,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 339102,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 339384,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 341716,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 342306,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 342411,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 342419,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 342429,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 342434,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 342559,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 342560,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 342625,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 342738,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 342945,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 343136,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 343149,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 343156,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 343358,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 343687,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 343728,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 343735,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 343774,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 343789,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 343794,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 344021,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 344324,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 345431,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 347341,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 347473,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 350596,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 350714,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 350729,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 350829,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 350900,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 351767,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 352003,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 353027,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 353770,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 354176,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 354531,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 354836,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 355431,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 356536,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 356954,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 357976,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 358115,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 358977,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 359113,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 360162,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 361802,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 362282,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 362296,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 362318,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 362695,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 363248,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 363343,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 363542,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 363544,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 365262,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 365306,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 365347,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 366990,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 367994,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 368720,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 368875,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 369370,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 369384,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 374189,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 376206,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 376790,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 376848,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 377574,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 380399,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 383075,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 383999,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 384037,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 385436,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 385494,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 385792,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 386977,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 388353,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 389423,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 390586,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 391178,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 391983,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 393354,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 394198,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 394213,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 394306,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 394360,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 394399,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 394409,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 394457,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 395238,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 395369,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 396324,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 396376,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 396568,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 396570,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 396576,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 396826,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 399923,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 399946,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 400512,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 402020,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 402740,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 402963,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 403790,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 405619,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 405857,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 406156,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 406778,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 406808,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 406868,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 407850,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 409931,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 410812,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 411080,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 413087,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 413092,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 415780,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 416412,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 417000,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 417444,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 418932,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 419892,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 426448,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 427287,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 428249,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 428405,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 429209,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 430419,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 431103,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 431264,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 432581,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 432671,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 433208,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 433567,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 434427,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 435201,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 435523,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 435583,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 435650,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 436787,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 439374,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 440073,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 441115,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 442348,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 442352,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 442408,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 442691,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 442696,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 442878,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 443202,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 443474,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 443932,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 445090,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 445648,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 445958,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 447310,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 448190,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 448954,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 452002,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 452877,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 452959,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 453024,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 453165,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 454606,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 456192,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 456874,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 456892,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 457963,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 458096,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 458759,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 458785,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 458786,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 458944,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 459144,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 459148,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 459611,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 459726,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 460162,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 460163,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 461401,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 462206,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 462322,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 462530,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 465578,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 468210,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 470246,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 471367,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 471383,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 471387,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 474973,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 475411,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 475416,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 475577,
    "seasonId": 1773,
    "clubId": 1803
  },
  {
    "playerId": 475589,
    "seasonId": 1773,
    "clubId": 2304
  },
  {
    "playerId": 477297,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 480741,
    "seasonId": 1773,
    "clubId": 1444
  },
  {
    "playerId": 482808,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 484062,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 484172,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 485102,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 485874,
    "seasonId": 1773,
    "clubId": 2175
  },
  {
    "playerId": 492205,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 503065,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 506280,
    "seasonId": 1773,
    "clubId": 1861
  },
  {
    "playerId": 508497,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 508498,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 512455,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 513086,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 513135,
    "seasonId": 1773,
    "clubId": 2771
  },
  {
    "playerId": 514093,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 515772,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 527168,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 534035,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 534175,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 534973,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 535689,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 536171,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 537975,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 540241,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 540919,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 543090,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 543529,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 543532,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 544583,
    "seasonId": 1773,
    "clubId": 1255
  },
  {
    "playerId": 545987,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 550568,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 560311,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 560313,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 563106,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 566675,
    "seasonId": 1773,
    "clubId": 1423
  },
  {
    "playerId": 574743,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 589537,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 614388,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 615881,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 616229,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 7088834,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 7089365,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 7090274,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 7090410,
    "seasonId": 1773,
    "clubId": 1503
  },
  {
    "playerId": 7091401,
    "seasonId": 1773,
    "clubId": 2263
  },
  {
    "playerId": 7091820,
    "seasonId": 1773,
    "clubId": 2121
  },
  {
    "playerId": 7091972,
    "seasonId": 1773,
    "clubId": 1461
  },
  {
    "playerId": 7092594,
    "seasonId": 1773,
    "clubId": 2188
  },
  {
    "playerId": 7092623,
    "seasonId": 1773,
    "clubId": 1570
  },
  {
    "playerId": 7092691,
    "seasonId": 1773,
    "clubId": 2689
  },
  {
    "playerId": 7092963,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 7093237,
    "seasonId": 1773,
    "clubId": 2833
  },
  {
    "playerId": 7103888,
    "seasonId": 1773,
    "clubId": 2501
  },
  {
    "playerId": 7104365,
    "seasonId": 1773,
    "clubId": 1680
  },
  {
    "playerId": 7104458,
    "seasonId": 1773,
    "clubId": 1281
  },
  {
    "playerId": 7105547,
    "seasonId": 1773,
    "clubId": 2157
  },
  {
    "playerId": 71458650,
    "seasonId": 1773,
    "clubId": 2771
  }
]
